# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
