# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
