# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_disabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='description',
            new_name='content',
        ),
    ]
